"""Add SHORT_NOTE content type, creatorprofiles.ext_id, user_topic_interests.source, posts.title nullable

Revision ID: add_shortnote_creator_extid_interest_source
Revises: add_curiosity_score_to_users
Create Date: 2026-07-17 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'shortnote_extid_source'
down_revision: Union[str, Sequence[str], None] = 'add_curiosity_score_to_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # SQLAlchemy stores enum *member names*, so the DB label is 'SHORT_NOTE'
    # (not 'short_note'). Enum value additions can't be autogenerated and must
    # be executed directly. PG12+ allows ADD VALUE inside a transaction as long
    # as the value isn't used in the same migration (it isn't here).
    op.execute("ALTER TYPE contenttype ADD VALUE IF NOT EXISTS 'SHORT_NOTE'")

    # creatorprofiles.ext_id — integer bridge to the ML artifacts
    op.add_column('creatorprofiles', sa.Column('ext_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_creatorprofiles_ext_id'), 'creatorprofiles', ['ext_id'], unique=True)

    # user_topic_interests.source — "onboarding" (explicit) vs implicit
    op.add_column('user_topic_interests', sa.Column('source', sa.String(length=30), nullable=True))

    # posts.title is optional (mcq/flashcard/short_note carry no title)
    op.alter_column('posts', 'title', existing_type=sa.String(length=200), nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # NOTE: reverting to NOT NULL will fail if any post has a NULL title.
    op.alter_column('posts', 'title', existing_type=sa.String(length=200), nullable=False)

    op.drop_column('user_topic_interests', 'source')

    op.drop_index(op.f('ix_creatorprofiles_ext_id'), table_name='creatorprofiles')
    op.drop_column('creatorprofiles', 'ext_id')

    # NOTE: PostgreSQL cannot DROP a value from an enum type. Removing
    # 'SHORT_NOTE' would require recreating the contenttype type and rewriting
    # every column that uses it, so it is intentionally left in place on
    # downgrade (a harmless unused label).
